### ISSUE TITLE
Linter does not load due to incorrect cmd

### ISSUE THREAD

**Issue by thegeorgeous** [codequest-eu/SublimeLinter-contrib-reek#4]
Installing and running the linter returns this message:
```
SublimeLinter: reek output:
ruby: no Ruby script found in input (LoadError) 
```
Seems like it has to do with https://github.com/codequest-eu/SublimeLinter-contrib-reek/pull/3/commits/9bfe8cd21931c69d79657aa275be02af21ec78f1

This was fixed in the Rubocop Linter in https://github.com/SublimeLinter/SublimeLinter-rubocop/commit/b9dad4fd. I don't understand why this regression bug was introduced.

**Comment by thegeorgeous** [comment]
@kruszczynski, I can open a PR if that's okay

**Comment by kruszczynski** [comment]
@thegeorgeous Either this change wasn't release yet when I was working on this plugin or I missed it 🙈.

I'm no longer at codequest therefore I no longer have admin access to this repo, but once you've opened a PR I'll try to ping some people to release this to package control.

✌🏽
